config/routes.rb
Rails.application.routes.draw do
  get 'authenticate/login'
  root 'authenticate#login'
  get 'authenticate/logout'
  post 'authenticate/login'
  resources :assignments
  resources :grades

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  belongs_to :teacher
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student
end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_secure_password
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_secure_password
  belongs_to :teacher
  has_many :parents
  has_many :grades

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_secure_password
  has_many :students
  has_many :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private def authenticate
    if session[:user_id].nil?
      redirect_to authenticate_login_path, notice: "You must login in order to proceed."
    end
  end
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assignment
      @assignment = Assignment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assignment_params
      params.require(:assignment).permit(:teacher_id, :name, :date_due)
    end
end

app/controllers/authenticate_controller.rb
class AuthenticateController < ApplicationController
  def login
    if request.post?
      unless params[:user_type].nil?
        user = params[:user_type].constantize
      else
        flash[:notice] = "Incorrect user name and password"
      end

      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        # user.find_by(email: params[:email])
        redirect_to assignments_path
        flash[:notice] = "You successfully logged in!"
      else
        flash[:notice] = "Wrong password. Please try again."
      end
    end
  end

  def logout
    session[:user_id] = nil
    redirect to authenticate_login_path, notice: "You successfully logged out!"
  end

  private
    def authenticate
    	if session[:user_id].nil?
    		redirect_to authenticate_login_path, notice: "You must login in order to proceed."
    	end
    end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :authenticate
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:student_id, :assignment_id, :grade)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/authenticate_helper.rb
module AuthenticateHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/assignments/_form.html.erb
<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% @assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.number_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date_due %><br>
    <%= f.date_select :date_due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<h1>Listing Assignments</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>Name</th>
      <th>Date due</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assignments.each do |assignment| %>
      <tr>
        <td><%= assignment.teacher_id %></td>
        <td><%= assignment.name %></td>
        <td><%= assignment.date_due %></td>
        <td><%= link_to 'Show', assignment %></td>
        <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>
        <td><%= link_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assignment', new_assignment_path %>

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form' %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher:</strong>
  <%= @assignment.teacher_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @assignment.name %>
</p>

<p>
  <strong>Date due:</strong>
  <%= @assignment.date_due %>
</p>

<%= link_to 'Edit', edit_assignment_path(@assignment) %> |
<%= link_to 'Back', assignments_path %>

app/views/authenticate/login.html.erb
<h1>Please Log In</h1>
  <%= form_tag do %>
    <p><%= email_field_tag :email, nil, placeholder: "Email" %></p>
    <p><%= password_field_tag :password, nil, placeholder: "Password" %></p>
    <%= submit_tag "Login Teacher", user_type: "Teacher" %>
    <%= submit_tag "Login Student", user_type: "Student"%>
    <%= submit_tag "Login Parent", user_type: "Parent"%>
  <% end %>

app/views/authenticate/logout.html.erb
<h1>Authenticate#logout</h1>
<p>Find me in app/views/authenticate/logout.html.erb</p>

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :assignment_id %><br>
    <%= f.number_field :assignment_id %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.text_field :grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<h1>Listing Grades</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Assignment</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.student_id %></td>
        <td><%= grade.assignment_id %></td>
        <td><%= grade.grade %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @grade.student_id %>
</p>

<p>
  <strong>Assignment:</strong>
  <%= @grade.assignment_id %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @grade.grade %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <p id="notice"><%= notice %></p>
    <title>Gradebook</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= yield %>

  </body>
  </html>